name: Daily Macro Update

on:
  schedule:
    - cron: "05 12 * * *"   # 09:05 Chile aprox (UTC-3). GitHub usa UTC
  workflow_dispatch:

defaults:
  run:
    working-directory: macro_tracker

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r macro_tracker/requirements.txt

      - name: Run pipeline
        run: |
          python macro_tracker/main.py

      - name: Publish snapshot to data repo
        env:
          TOKEN: ${{ secrets.DATA_REPO_TOKEN }}
          OWNER: bcorrv
          DATA_REPO: investmentlab-data
        run: |
          git clone https://$TOKEN@github.com/$OWNER/$DATA_REPO.git out
          cp macro_tracker/data/daily_snapshot.csv out/daily_snapshot.csv
          cd out
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add daily_snapshot.csv
          git commit -m "Update daily_snapshot" || echo "No changes"
          git push

